In [122]:
import os
import sys
import numpy as np 
import pandas as pd
import geopandas as gpd

sys.path.append("../utils")

import config

pd.set_option("display.max_columns", None)

In [123]:
# OLD GEOMETRIES -- don't use these.

# def read_geojson_with_geopandas(file_path):
#         gdf = gpd.read_file(file_path)
#         return gdf

# insp_19 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2019.geojson")
# insp_20 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2020.geojson")
# insp_21 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2021.geojson")
# insp_22 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2022.geojson")
# insp_23 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2023.geojson")

In [124]:
# Loading in inspections data with newly calculated geometries 4/28/25

insp_19 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2019.geojson"
)
insp_20 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2020.geojson"
)
insp_21 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2021.geojson"
)
insp_22 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2022.geojson"
)
insp_23 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2023.geojson"
)

In [125]:
insp_19.head()

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,longitude,report_tit,globalid,calculated,inspectorp,inspection,addressvis,address_su,address_th,address__1,address_lo,address__2,address_ad,address_po,address_co,address_fu,calfireuni,county,community,community_,battalion,enginenumb,stationnam,stationn_1,shift,occupantho,deliveryno,inspecti_1,a_removebr,b_removele,c_removede,d_removede,e_removedy,f_removefl,g_relocate,h_cutannua,i_reducefu,j_allexpos,k_deaddyin,l_logsstum,m_outbuild,n_addressd,o_chimneys,recommend_,propanetan,accessegre,waterstora,water_sour,can_engine,water_stor,water_comm,structuret,roofconstr,eaves,ventscreen,exteriorsi,windowpane,deckporchg,deckporche,patiocover,fenceattac,utilitymis,utilitym_1,nonhabitab,escalateto,reinspecti,clearreins,citationnu,citationda,deadtrees3,photoid,photoid_ca,le100numbe,inspecti_2,coredatafl,partner_di,principal_,firescopei,responsibi,yearbuilt,siteaddres,numberofst,appenddate,editstatus,createddat,createdby,editeddate,editedby,textfield1,textfield2,numberfiel,numberfi_1,core_with_,Date,apn,geometry
0,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,2018-05-25 16:25:06,2019-06-05 11:57:49,2019-05-07 11:52:36,2019-06-05 16:35:26,2.0,Compliant,None,None,34.669616,-120.031160,Defensible Space Inspection Report,None,None,DSI,2019-06-05,Yes - Without Reflective,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,SBC,SBA,Woodstock,None,2,32,32,None,None,Yes,Hardcopy,30 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Private Hydrant- Private Stored Water,yes,Over 5000 gallons,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Wood,No Windows,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',0,0,None,NaT,None,None,None,0,None,None,0.0,0.0,None,None,None,None,None,2000.0,None,0.0,2019-06-05,None,None,None,None,None,None,None,0.0,0.0,None,2019-06-05,141-010-040,"POLYGON ((-2813.179 -371821.557, -2813.179 -37..."
1,7f9b6d98-548d-4b94-97c6-82cbddf84d99,2018-05-25 16:25:10,2019-05-15 12:26:44,2019-05-07 11:52:37,2019-05-15 12:26:45,3.0,Compliant,None,None,34.679129,-120.091914,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,CA,93460,US,3290 Avenida Caballo Santa Ynez Santa Barbara ...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,yes,Private Hydrant- Private Stored Water,yes,None,None,Single Family Residence Multi Story,Metal,No Eaves,No Vents,Wood,Single Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',1,0,None,NaT,None,None,None,None,f1556c16-78c8-44bf-b6ce-a7ddb5908d96,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,135-310-022,"POLYGON ((-8368.416 -370860.259, -8475.394 -37..."
2,03afdf39-173a-4f02-bfdc-e0725e554959,2018-05-25 16:25:11,2019-05-09 14:20:04,2019-05-07 11:52:37,2019-05-09 15:26:24,2.0,Compliant,None,None,34.676197,-120.089553,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,None,None,None,None,None,Single Family Residence Multi Story,Tile,Unenclosed,No Vents,Stucco/Brick/Cement,Multi Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,>50',2,0,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,135-310-075,"POLYGON ((-8253.618 -371073.707, -8136.129 -37..."
3,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,2018-05-25 16:25:11,2019-05-09 14:25:18,2019-05-07 11:52:38,2019-05-09 15:26:26,2.0,Compliant,None,None,34.677982,-120.088944,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,Yes,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,no,None,None,None,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Metal,Single Pane,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,No Fence,None,0,0,None,NaT,None,None,None,None,17322007-d5d1-4568-bde6-00ae169a0bbf,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,135-310-075,"POLYGON ((-8201.866 -370989.432, -8201.866 -37..."
4,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,2018-05-25 16:25:11,2019-12-17 14:16:14,2019-05-07 11:52:38,2019-12-18 11:43:23,5.0,Compliant,None,None,34.678469,-120.087539,Defensible Space Inspection Report,None,None,DSI,2019-12-17,Yes - Without Reflective,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3320 A Canada Este Rd Santa Ynez Santa Barbara...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Hardcopy,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Pond,None,None,None,Single Family Residence Multi Story,Asphalt,Unenclosed,"Mesh Screen > 1/8""",Wood,Single Pane,Masonry/Concrete,No Deck/Porch,Non Combustible,No Fence,None,0,0,None,NaT,None,None,None,None,50114b4c-e04a-4054-bd54-5a7dbca535af,None,0.0,0.0,None,None,None,None,None,2002.0,None,0.0,2019-05-08,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-17,135-310-042,"POLYGON ((-7966.144 -370818.558, -7966.144 -37..."

In [126]:
rows19 = len(insp_19)
rows20 = len(insp_20)
rows21 = len(insp_21)
rows22 = len(insp_22)
rows23 = len(insp_23)

uncleaned_length = rows19 + rows20 + rows21 + rows22 + rows23
print(uncleaned_length)

89357

In [127]:
# Select only necessary columns. Columns in 2023 dataframe are different, but will be renamed in a later chunk

needed_columns = [
    "system_cre",
    "status",
    "latitude",
    "longitude",
    "address_su",
    "address_th",
    "address__1",
    "address_lo",
    "address__2",
    "address_po",
    "address_fu",
    "Date",
    "geometry",
    "inspection",
    "structuret"
]
needed_columns_23 = [
    "updated_at",
    "status",
    "latitude",
    "longitude",
    "address_sub_thoroughfare",
    "address_thoroughfare",
    "address_suite",
    "address_locality",
    "address_sub_admin_area",
    "address_postal_code",
    "address_full",
    "Date",
    "geometry",
    "inspectiondate_calculate",
    "structuretype"
]

In [128]:
# Narrow down all inspections dataframes to the necessary columns defined above

insp_19_clean = insp_19[needed_columns]
insp_20_clean = insp_20[needed_columns]
insp_21_clean = insp_21[needed_columns]
insp_22_clean = insp_22[needed_columns]
insp_23_clean = insp_23[needed_columns_23]

In [129]:
# Rename 2023 dataframe columns to match the others

colnames_23 = [
    "system_cre",
    "status",
    "latitude",
    "longitude",
    "address_su",
    "address_th",
    "address__1",
    "address_lo",
    "address__2",
    "address_po",
    "address_fu",
    "Date",
    "geometry",
    "inspection",
    "structuret"
]

insp_23_clean.columns = colnames_23

# verify column names change
print(insp_23_clean.columns.tolist())

['system_cre', 'status', 'latitude', 'longitude', 'address_su', 'address_th', 'address__1', 'address_lo', 'address__2', 'address_po', 'address_fu', 'Date', 'geometry', 'inspection', 'structuret']

In [130]:
# Adding inspection year column

insp_19_clean['year'] = 2019
insp_20_clean['year'] = 2020
insp_21_clean['year'] = 2021
insp_22_clean['year'] = 2022
insp_23_clean['year'] = 2023

/Users/jpcohen/.conda/envs/wildfire_prep/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/jpcohen/.conda/envs/wildfire_prep/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/jpcohen/.conda/envs/wildfire_prep/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/jpcohen/.conda/envs/wildfire_prep/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/jpcohen/.conda/envs/wildfire_prep/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [131]:
# Joining all inspections dataframes

all_inspections = pd.concat([insp_19_clean, insp_20_clean, insp_21_clean, insp_22_clean, insp_23_clean], axis=0, ignore_index=True)

# converting 'system_cre' column to display single days, instead of days and times
all_inspections["system_cre"] = pd.to_datetime(all_inspections["system_cre"]).dt.date

In [132]:
all_inspections.head()

,system_cre,status,latitude,longitude,address_su,address_th,address__1,address_lo,address__2,address_po,address_fu,Date,geometry,inspection,structuret,year
0,2019-05-07,Compliant,34.669616,-120.031160,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,93460,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,2019-06-05,"POLYGON ((-2813.179 -371821.557, -2813.179 -37...",2019-06-05,Utility or Miscellaneous Structure > 120 sqft,2019
1,2019-05-07,Compliant,34.679129,-120.091914,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,93460,3290 Avenida Caballo Santa Ynez Santa Barbara ...,2019-05-09,"POLYGON ((-8368.416 -370860.259, -8475.394 -37...",2019-05-09,Single Family Residence Multi Story,2019
2,2019-05-07,Compliant,34.676197,-120.089553,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,93460,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,"POLYGON ((-8253.618 -371073.707, -8136.129 -37...",2019-05-09,Single Family Residence Multi Story,2019
3,2019-05-07,Compliant,34.677982,-120.088944,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,93460,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,"POLYGON ((-8201.866 -370989.432, -8201.866 -37...",2019-05-09,Utility or Miscellaneous Structure > 120 sqft,2019
4,2019-05-07,Compliant,34.678469,-120.087539,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,93460,3320 A Canada Este Rd Santa Ynez Santa Barbara...,2019-12-17,"POLYGON ((-7966.144 -370818.558, -7966.144 -37...",2019-12-17,Single Family Residence Multi Story,2019

In [133]:
# rename columns to be more readable

rename_map = {
    "system_cre": "system_created",
    "status": "inspection_status",
    "latitude": "latitude",
    "longitude": "longitude",
    "address_su": "address_number",
    "address_th": "street",
    "address__1": "apt_number",
    "address_lo": "city",
    "address__2": "county",
    "address_ad": "state",
    "address_po": "zip_code",
    "address_co": "country",
    "address_fu": "address_full",
    "Date": "date",
    "geometry": "geometry",
    "inspection": "inspection_date",
    "structuret": "structure_type"
}

all_inspections = all_inspections.rename(columns=rename_map)

In [134]:
# Some dates in the 'inspection' column have the format '2023-08-22 00:00:00'.
# This chunk is to remove the occurrences of '00:00:00' and remove trailing whitespace.

all_inspections["inspection_date"] = (
    all_inspections["inspection_date"]
    .astype(str)
    .str.replace(" 00:00:00", "", regex=False)
    .str.strip()
)

In [135]:
all_inspections.head()

,system_created,inspection_status,latitude,longitude,address_number,street,apt_number,city,county,zip_code,address_full,date,geometry,inspection_date,structure_type,year
0,2019-05-07,Compliant,34.669616,-120.031160,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,93460,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,2019-06-05,"POLYGON ((-2813.179 -371821.557, -2813.179 -37...",2019-06-05,Utility or Miscellaneous Structure > 120 sqft,2019
1,2019-05-07,Compliant,34.679129,-120.091914,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,93460,3290 Avenida Caballo Santa Ynez Santa Barbara ...,2019-05-09,"POLYGON ((-8368.416 -370860.259, -8475.394 -37...",2019-05-09,Single Family Residence Multi Story,2019
2,2019-05-07,Compliant,34.676197,-120.089553,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,93460,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,"POLYGON ((-8253.618 -371073.707, -8136.129 -37...",2019-05-09,Single Family Residence Multi Story,2019
3,2019-05-07,Compliant,34.677982,-120.088944,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,93460,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,"POLYGON ((-8201.866 -370989.432, -8201.866 -37...",2019-05-09,Utility or Miscellaneous Structure > 120 sqft,2019
4,2019-05-07,Compliant,34.678469,-120.087539,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,93460,3320 A Canada Este Rd Santa Ynez Santa Barbara...,2019-12-17,"POLYGON ((-7966.144 -370818.558, -7966.144 -37...",2019-12-17,Single Family Residence Multi Story,2019

In [136]:
# adding address_id to be unique for every unique inspection
all_inspections["address_id"] = np.arange(1, len(all_inspections) + 1)

In [137]:
# Fixing CRS to 3310, Albers

all_inspections = all_inspections.to_crs(epsg=3310)

print(all_inspections.crs)

EPSG:3310

In [138]:
# all_inspections.to_file(
#     "/capstone/wildfire_prep/data/MASTER_DATAFRAME/inspections_master.geojson",
#     driver="GeoJSON",
# )

# all_inspections.to_file(
#     "/capstone/wildfire_prep/data/MASTER_DATAFRAME/inspections_master_copy.geojson",
#     driver="GeoJSON",
# )

BREAKPOINT

In [139]:
# Import parcel data

# parcels = os.path.join(config.data_dir, "parcel_boundaries", "cbiinputs.gdb")
# parcels = gpd.read_file(parcels).to_crs(config.albers_crs)

In [140]:
# Checking parcel column names, and narrowing down the dataframe to only necessary columns

# print(parcels.columns.tolist())

# parcels_copy = parcels.copy()

# parcel_columns = ['situs1', 'shape_leng', 'shape_Length', 'shape_Area', 'geometry']
# parcels_copy = parcels[parcel_columns]

In [141]:
# Joining parcels to inspections dataframe 

# inspections_parcels = gpd.sjoin(
#         parcels_copy, all_inspections_copy, how="inner", predicate="contains")

In [142]:
# inspections_parcels.drop("index_right", axis=1, inplace=True)

In [143]:
# buffered_buildings = read_geojson_with_geopandas('/capstone/wildfire_prep/data/joined_inspections_parcels/buffered_buildings_2022.geojson')

In [144]:
# buffered_buildings_copy = buffered_buildings.copy()

# print(buffered_buildings.columns.tolist())

# buff_buildings_columns = ['geometry']

# buffered_buildings_copy = buffered_buildings_copy[buff_buildings_columns]

In [145]:
# inspections_buffbuildings = gpd.sjoin(
#         buffered_buildings_copy, all_inspections_copy, how="inner", predicate="contains")

In [146]:
# inspections_buffbuildings.drop("index_right", axis=1, inplace=True)

/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id

In [147]:
# inspections_buffbuildings.to_file(
#     "/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id/inspections_buffered_buildings.geojson",
#     driver="GeoJSON",
# )

# inspections_parcels.to_file(
#     "/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id/inspections_parcels.geojson",
#     driver="GeoJSON",
# )

In [148]:
# making a dataframe with ALL columns from the inspection data. This cannot include 2023 data, as the column names had changed.

# inspections_no_2023 = pd.concat(
#     [insp_19, insp_20, insp_21, insp_22],
#     axis=0,
#     ignore_index=True,
# )

# inspections_no_2023 = inspections_no_2023.to_crs(epsg=3310)

# inspections_no_2023.head()

In [149]:
# inspections_no_2023 = gpd.sjoin(
#     buffered_buildings_copy, inspections_no_2023, how="inner", predicate="contains"
# )

# inspections_no_2023.shape

In [150]:
# inspections_no_2023.to_file(
#     "/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id/inspections_buffbuild_no_2023.geojson",
#     driver="GeoJSON",
# )

In [151]:
print("Percent of values in columns that are unique: \n")
for col in insp_21:
    print(
        f"{col}: {
            round(
                (insp_21[col].unique().shape[0])/(len(insp_21)) * 100, 
                4)
            }%"
    )

Percent of values in columns that are unique:

fulcrum_id: 74.8583%
created_at: 20.9719%
updated_at: 74.6926%
system_cre: 11.205%
system_upd: 73.88%
version: 0.0428%
status: 0.0107%
project: 0.0053%
assigned_t: 0.0053%
latitude: 72.5061%
longitude: 72.8002%
report_tit: 0.0053%
globalid: 0.0053%
keyid: 0.0053%
propertyst: 0.0053%
inspection: 0.0053%
inspectorp: 0.016%
inspecti_1: 0.6201%
addressvis: 0.0214%
address_su: 26.3659%
address_th: 5.4742%
address__1: 0.0267%
address_lo: 0.1123%
address__2: 0.016%
address_ad: 0.0267%
address_po: 0.0909%
address_co: 0.0267%
address_fu: 65.0005%
calfireuni: 0.0053%
county: 0.0053%
community: 0.3261%
community_: 0.0053%
battalion: 0.016%
enginenumb: 0.1283%
stationnam: 0.0855%
shift: 0.0321%
accessegre: 0.0107%
occupantho: 0.0107%
deliveryno: 0.016%
inspecti_2: 0.0267%
a_removebr: 0.0107%
b_removele: 0.0107%
c_removede: 0.0107%
d_removede: 0.0107%
e_removefl: 0.0107%
f_removefl: 0.0107%
g_relocate: 0.0107%
h_cutannua: 0.0107%
i_removefu: 0.0107%
j_exposedw: 0.0107%
k_removede: 0.0107%
l_removelo: 0.0107%
m_outbuild: 0.0107%
n_displaya: 0.0107%
o_stovepip: 0.0107%
recommendc: 0.016%
waterstora: 0.016%
water_sour: 0.5774%
can_engine: 0.016%
water_stor: 0.0321%
water_comm: 1.2937%
structuret: 0.0802%
structureh: 0.0267%
roofconstr: 0.0428%
eaves: 0.0267%
ventscreen: 0.0321%
exteriorsi: 0.0374%
windowpane: 0.0267%
deckporchg: 0.0267%
deckporche: 0.0267%
patiocover: 0.0214%
fenceattac: 0.0267%
propanetan: 0.0374%
utilitymis: 0.0214%
utilitym_1: 0.0642%
nonhabitab: 0.0588%
escalateto: 0.0053%
reinspecti: 0.0053%
citationnu: 0.0053%
number_of_: 0.0588%
photoid: 0.1069%
photoid_ca: 0.0267%
le100numbe: 0.0053%
inspecti_3: 0.0053%
coredata: 0.0053%
firescopei: 0.0053%
responsibi: 0.0107%
yearbuilt: 0.6789%
siteaddres: 0.0053%
numberofst: 0.0053%
appenddate: 0.0053%
editstatus: 0.0053%
calculated: 0.0053%
calculat_1: 0.0053%
calculat_2: 0.0053%
textfield1: 0.0053%
textfield2: 0.0053%
numberfiel: 0.0053%
numberfi_1: 0.0053%
previousyr: 0.0053%
previous_1: 0.0053%
calculat_3: 0.0053%
calculat_4: 0.0053%
creationda: 0.6148%
editdate: 0.9462%
creator: 0.0053%
editor: 0.0053%
Date: 0.6201%
apn: 63.1241%
geometry: 83.2407%

#### Josh's opinion

Keep columns by default if they have (or at least mark them for likely usefulness)...
* % unique values > 0.1% 
* % unique values < 80%

For the rest of the columns, investigate whether to keep them on a case by case basis...
* high uniqueness may indicate some kind of unique identifier
* low uniqueness column may still be important