In [11]:
import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import geopandas as gpd
import rioxarray as rioxr
from shapely import box

import pystac_client
import planetary_computer

from IPython.display import Image


sys.path.append("../utils")

pd.set_option("display.max_columns", None)

In [12]:
in19 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2019.geojson"
)
in20 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2020.geojson"
)
in21 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2021.geojson"
)
in22 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2022.geojson"
)
in23 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2023.geojson"
)

In [13]:
# structuret

colnames_23 = {
    "system_created_at": "system_cre",
    "address_suite": "address_su",
    "address_thoroughfare": "address_th",
    "address_locality": "address_lo",
    "address_sub_admin_area": "address__2",
    "address_postal_code": "address_po",
    "address_full": "address_fu",
    "inspectiondate_calculate": "inspection",
    "structuretype": "structuret",
    "address_admin_area": "address_ad",
    "address_country": "address_co",
}

in23 = in23.rename(columns=colnames_23)

In [14]:
inspections = pd.concat([in19, in20, in21, in22, in23], axis=0, ignore_index=True)

/tmp/ipykernel_572262/1430165923.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  inspections = pd.concat([in19, in20, in21, in22, in23], axis=0, ignore_index=True)

In [15]:
in23.head(20)

,fulcrum_id,created_at,updated_at,created_by,updated_by,system_cre,system_updated_at,version,status,project,assigned_to,latitude,longitude,report_title,globalid,keyid,propertystatus,inspectionstatus,inspectorfirstname,inspectorlastname,prevention_inspectorfirstname,prevention_inspectorfirstname_other,prevention_inspectorlastname,prevention_inspectorlastname_other,inspectorposition,inspection,addressvisible,address_sub_thoroughfare,address_th,address_su,address_lo,address__2,address_ad,address_po,address_co,address_fu,calfireunit,county,community,community_other,battalion,enginenumber,stationname,shift,shift_julian,accessegress,occupanthome,deliverynotificationmethod,inspectionhours,a_removebranchesfromstovepipe,b_removeleavesneedlesveg,c_removedeaddyingtrees,d_removedeaddyinggrassplants,e_removeflammablegroundcover,f_removeflammablevegetation,g_relocateexposedwoodpiles,h_cutannualgrassesforbs,i_removefuelsusingctguidelines,j_exposedwoodpiles,k_removedeaddyingwoodyfuels,l_removelogstumpsembeddedsoil,m_outbuildingsliquidpropanegas,n_displayaddresscontrasting,o_stovepipemetalscreenopenings,recommendclearvegetation,waterstora,water_source,can_engine_access_water_source,water_storage_size_stored_water_on_individual_parcels_only,water_comments,structuret,structurehabitable,roofconstruction,eaves,ventscreen,exteriorsiding,windowpane,deckporchgrade,deckporchelevated,patiocovercarport,fenceattachedtostructure,propanetankdistance,utilitymiscstructuredistance,utilitymiscstucturecount,nonhabitableoutbuildings,escalatetocoordinator,reinspectiondate,citationnumber,number_of_dead_trees_within_300_ft_of_residence,gatecode,comments,photoid,photoid_caption,photoid_url,le100number,inspectioncount,coredata,firescopeid,apn,yearbuilt,siteaddress,numberofstructures,appenddate,editstatus,calculatedglobalid,calculateddate,calculateduid,textfield1,textfield2,numberfield1,numberfield2,previousyrinspecteddata,previousyrinspectionstatus,calculatededitor,calculatededitdate,creationdate,editdate,creator,editor,Date,geometry
0,48c58877-f0ce-438d-ac87-6434a2c15fe8,2022-02-13 16:00:00,2023-06-05 17:00:00,gis@sbcfire.com,gis@sbcfire.com,2022-02-14 10:44:17,2023-12-06 08:54:05,13,Compliant,None,None,34.461625,-119.772555,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-06-05,Yes - Without Reflective,4440,Shadow Hills Cir,None,Santa Barbara,Santa Barbara,CA,93105,US,4440 Shadow Hills Cir Santa Barbara Santa Barb...,SBC,SBA,San Marcos Foothills,None,1,NaN,13,A,157,Yes,No,Mailed,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Hydrant- Municipal/Public Water Supply,yes,None,None,Multi Family Residence Multi Story,Habitable,Tile,Enclosed,"Mesh Screen <= 1/8""",Other,Single Pane,Masonry/Concrete,Masonry/Concrete,Non Combustible,No Fence,Not Applicable,None,0,0,None,NaT,None,0,None,None,"eb994fe9-6273-444c-95b7-c3633b0876f5,de1dc62a-...",",,",https://web.fulcrumapp.com/photos/view?photos=...,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-02-14,2022-02-14,None,None,2023-06-05,POINT (-119.77256 34.46163)
1,f351800c-fc5c-4b79-bf24-a41775b74d7c,2022-04-04 17:00:00,2023-10-06 09:47:59,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:06,2023-10-06 09:55:52,8,Compliant,None,None,34.672591,-120.108711,Defensible Space Inspection Report,None,0.0,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3110 A,Acampo Rd,None,Santa Ynez,Santa Barbara,CA,93441,US,3110 A Acampo Rd Santa Ynez Santa Barbara CA 9...,SBC,SBA,Los Olivos,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),B,279,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Hydrant- Municipal/Public Water Supply,yes,None,None,Single Family Residence Single Story,Habitable,Tile,Unenclosed,No Vents,Stucco/Brick/Cement,Single Pane,Masonry/Concrete,No Deck/Porch,Combustible,Combustible,Not Applicable,None,0,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,1980.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,2020-07-08,None,None,2023-10-06,POINT (-120.10871 34.67259)
2,b97b5b98-bda4-4b41-b850-3fdb36c9f689,2022-04-04 17:00:00,2023-10-06 09:39:32,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:07,2023-10-06 09:54:37,8,Compliant,None,None,34.668610,-120.115221,Defensible Space Inspection Report,None,0.0,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3035,Figueroa Mountain Rd,None,Santa Ynez,Santa Barbara,CA,93441,US,3035 Figueroa Mountain Rd Santa Ynez Santa Bar...,SBC,SBA,Los Olivos,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),B,279,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Hydrant- Municipal/Public Water Supply,yes,None,None,Single Family Residence Single Story,Habitable,Asphalt,Unenclosed,"Mesh Screen > 1/8""",Wood,Multi Pane,Masonry/Concrete,No Deck/Porch,Combustible,No Fence,Not Applicable,None,0,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,1991.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,2020-07-08,None,None,2023-10-06,POINT (-120.11522 34.66861)
3,03dfcea7-bf0a-461f-92a0-42ac0d84d6ed,2022-04-04 17:00:00,2023-10-06 09:40:52,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:07,2023-10-06 09:54:45,8,Compliant,None,None,34.669655,-120.115747,Defensible Space Inspection Report,None,0.0,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3055,Figueroa Mountain Rd,None,Los Olivos,Santa Barbara,CA,93441,US,3055 Figueroa Mountain Rd Los Olivos Santa Bar...,SBC,SBA,Los Olivos,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),B,279,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Hydrant- Municipal/Public Water Supply,yes,None,None,Single Family Residence Multi Story,Habitable,Asphalt,Enclosed,"Mesh Screen > 1/8""",Wood,Multi Pane,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,Combustible,Not Applicable,None,0,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,2020-07-08,None,None,2023-10-06,POINT (-120.11575 34.66966)
4,e7d6b19a-e26b-4041-9a52-2138aed4d439,2022-04-04 17:00:00,2023-10-06 09:41:16,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:07,2023-10-06 09:54:47,8,Compliant,None,None,34.670898,-120.117483,Defensible Space Inspection Report,None,0.0,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3150 A,Calkins Rd,None,Los Olivos,Santa Barbara,CA,93441,US,3150 A Calkins Rd Los Olivos Santa Barbara CA ...,SBC,SBA,Los Olivos,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),B,279,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,"Hydrant- Municipal/Public Water Supply,Pool",yes,None,None,Single Family Residence Single Story,Habitable,Tile,Unenclosed,"Mesh Screen > 1/8""",Stucco/Brick/Cement,Single Pane,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,No Fence,Not Applicable,None,0,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,2020-07-08,None,None,2023-10-06,POINT (-120.11748 34.6709)
5,d72e7a31-b481-433b-ae4b-6e7300f948de,2022-04-04 17:00:00,2023-10-06 09:42:33,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:07,2023-10-06 09:54:56,8,Compliant,None,None,34.670428,-120.119241,Defensible Space Inspection Report,None,0.0,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3075,Calkins Rd,None,Los Olivos,Santa Barbara,CA,93441,US,3075 Calkins Rd Los Olivos Santa Barbara CA 93...,SBC,SBA,Los Olivos,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),B,279,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,"Hydrant- Municipal/Public Water Supply,Private...",yes,None,None,Single Family Residence Single Story,Habitable,Asphalt,Unenclosed,No Vents,Wood,Single Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,Not Applicable,>50',1,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,1988.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,2020-07-08,None,None,2023-10-06,POINT (-120.11924 34.67043)
6,f55fbbeb-23e5-4989-a9b0-38fcf29111d1,2022-04-04 17:00:00,2023-10-06 09:43:23,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:07,2023-10-06 09:55:01,8,Compliant,None,None,34.671502,-120.119875,Defensible Space Inspection Report,None,0.0,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3131,Calkins Rd,None,Los Olivos,Santa Barbara,CA,93441,US,3131 Calkins Rd Los Olivos Santa Barbara CA 93...,SBC,SBA,Los Olivos,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),B,279,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,"Hydrant- Municipal/Public Water Supply,Pool,Tank",yes,None,None,Single Family Residence Multi Story,Habitable,Asphalt,Enclosed,"Mesh Screen > 1/8""",Stucco/Brick/Cement,Multi Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,Not Applicable,>50',3,1,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,1990.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,2020-07-08,None,None,2023-10-06,POINT (-120.11988 34.6715)
7,8a0bb83b-aa8a-4b11-9488-ae1ebc3a6b48,2018-05-23 17:00:00,2023-10-19 11:14:17,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:08,2023-10-24 07:57:42,3,Compliant,None,None,34.747729,-120.028376,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-10-19,No - Not Visible,7445,Figueroa Mountain Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,7445 Figueroa Mountain Rd Santa Ynez Santa Bar...,SBC,SBA,Figueroa Mountain,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),B,292,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Private Hydrant- Private Stored Water,yes,None,None,Single Family Residence Multi Story,Habitable,Asphalt,No Eaves,No Vents,Wood,Multi Pane,No Deck/Porch,Wood,Combustible,No Fence,>30',>50',1,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,1800.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-10-19,2020-08-11,None,None,2023-10-19,POINT (-120.02838 34.74773)
8,854ca08e-5d8c-4cae-b778-a8f8f0b63be3,2018-05-23 17:00:00,2023-10-19 11:14:05,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:08,2023-10-24 07:57:41,3,Compliant,None,None,34.747324,-120.027858,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-10-19,No - Not Visible,7445,Figueroa Mountain Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,7445 Figueroa Mountain Rd Santa Ynez Santa Bar...,SBC,SBA,Figueroa Mountain,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),B,292,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Private Hydrant- Private Stored Water,yes,None,None,Single Family Residence Single Story,Habitable,Metal,Unenclosed,"Mesh Screen > 1/8""",Wood,Multi Pane,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,Combustible,>30',None,0,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,1800.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-10-19,2020-08-11,None,None,2023-10-19,POINT (-120.02786 34.74732)
9,b4264e70-1c57-41a3-a6b0-ccc668504393,2018-05-23 17:00:00,2023-10-19 11:11:49,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:08,2023-10-24 07:57:39,3,Compliant,None,None,34.746687,-120.028255,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-10-19,Yes - Without Reflective,7445,Figueroa Mountain Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,7445 Figueroa Mountain Rd Santa Ynez Santa Bar...,SBC,SBA,Figueroa Mountain,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),B,292,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Private Hydrant- Private Stored Water,yes,None,None,Single Family Residence Multi Story,Habitable,Metal,No Eaves,No Vents,Wood,Multi Pane,No Deck/Porch,Wood,No Patio Cover/Carport,No Fence,>30',>50',3,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,1800.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-10-19,2020-08-11,None,None,2023-10-19,POINT (-120.02826 34.74669)
10,5f6126d5-6dcf-4676-8802-1d3e58649c59,2022-04-04 17:00:00,2023-08-01 09:43:18,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:08,2023-08-01 09:47:57,6,Compliant,None,None,34.631475,-120.000829,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-07-31,Yes - Without Reflective,1680,Alisos Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,1680 Alisos Rd Santa Ynez Santa Barbara CA 934...,SBC,SBA,Happy Canyon,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),A,213,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Single Family Residence Single Story,Habitable,Tile,Unenclosed,No Vents,Stucco/Brick/Cement,Single Pane,No Deck/Porch,No Deck/Porch,Combustible,No Fence,>30',None,0,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-08-10,2020-07-21,None,None,2023-07-31,POINT (-120.00083 34.63148)
11,77500807-7f86-4444-84b1-31a0864517e0,2022-04-04 17:00:00,2023-08-01 09:43:07,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:08,2023-08-01 09:47:09,6,Compliant,None,None,34.628198,-120.000097,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-07-31,Yes - Without Reflective,1550,Alisos Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,1550 Alisos Rd Santa Ynez Santa Barbara CA 934...,SBC,SBA,Happy Canyon,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),A,213,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,"Pond,Pool",yes,None,None,Single Family Residence Single Story,Habitable,Asphalt,Unenclosed,No Vents,Wood,Single Pane,Masonry/Concrete,No Deck/Porch,Combustible,No Fence,>30',None,0,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,1960.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-08-10,2020-07-21,None,None,2023-07-31,POINT (-120.0001 34.6282)
12,fd30953b-7581-44b7-8320-2ae1b15c7184,2022-04-04 17:00:00,2023-08-01 09:44:36,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:09,2023-08-01 09:48:17,6,Compliant,None,None,34.627765,-119.994534,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-07-31,No - Not Visible,1520,Alisos Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,1520 Alisos Rd Santa Ynez Santa Barbara CA 934...,SBC,SBA,Happy Canyon,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),A,213,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,no,None,None,None,None,Single Family Residence Single Story,Habitable,Asphalt,Unenclosed,"Mesh Screen <= 1/8""",Wood,Multi Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,Not Applicable,None,0,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-08-10,2020-08-10,None,None,2023-07-31,POINT (-119.99453 34.62777)
13,ffd2ee07-9a4e-4b4c-9fc5-451f76ccf15e,2022-04-04 17:00:00,2023-08-01 10:08:33,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:09,2023-08-01 10:16:43,6,Compliant,None,None,34.630104,-119.979618,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-07-31,No - Not Visible,6885 A,Happy Canyon Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,6885 A Happy Canyon Rd Santa Ynez Santa Barbar...,SBC,SBA,Happy Canyon,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),A,213,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Private Hydrant- Private Stored Water,yes,None,None,Single Family Residence Single Story,Habitable,Tile,Unenclosed,"Mesh Screen <= 1/8""",Wood,Single Pane,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,Non Combustible,Not Applicable,<30',1,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-08-10,2020-08-11,None,None,2023-07-31,POINT (-119.97962 34.6301)
14,81f65302-d2ad-43f5-878c-c0a125681865,2022-04-04 17:00:00,2023-08-01 10:08:43,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:09,2023-08-01 10:16:44,6,Compliant,None,None,34.629939,-119.976518,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-07-31,No - Not Visible,6945,Happy Canyon Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,6945 Happy Canyon Rd Santa Ynez Santa Barbara ...,SBC,SBA,Happy Canyon,None,3,32.0,32,A,213,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Utility or Miscellaneous Structure > 120 sqft,Habitable,Metal,No Eaves,No Vents,Other,No Windows,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,Not Applicable,>50',3,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-08-10,2020-08-11,None,None,2023-07-31,POINT (-119.97652 34.62994)
15,b702f026-f41d-4547-94bd-864cf8b2ace0,2022-04-04 17:00:00,2023-08-01 10:09:05,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:09,2023-08-01 10:16:53,6,Compliant,None,None,34.631404,-119.975815,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-07-31,No - Not Visible,6945 A,Happy Canyon Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,6945 A Happy Canyon Rd Santa Ynez Santa Barbar...,SBC,SBA,Happy Canyon,None,3,32.0,Santa Ynez Valley (Outside Engine Co. Area),A,213,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Pool,yes,None,None,Single Family Residence Single Story,Habitable,Tile,Unenclosed,No Vents,Wood,Single Pane,Masonry/Concrete,No Deck/Porch,Combustible,No Fence,>30',None,0,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-08-10,2020-08-11,None,None,2023-07-31,POINT (-119.97581 34.6314)

In [16]:
inspections["inspection_id"] = np.arange(1, len(inspections) + 1)

/Users/ryangreen/.conda/envs/prg/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super().__setitem__(key, value)

In [17]:
inspections = inspections[["inspection_id", "structuret"]]

In [18]:
structuretype_codes = (
    inspections[["structuret"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

structuretype_codes["structure_code"] = range(100, 100 + len(structuretype_codes))

structuretype_codes

                                       structuret  structure_code
0   Utility or Miscellaneous Structure > 120 sqft             100
1             Single Family Residence Multi Story             101
2            Single Family Residence Single Story             102
3                                Unable to Assess             103
4                Commercial Building Single Story             104
5             Infrastructure (Essential Services)             105
6                         Mobile Home Double Wide             106
7             Multi Family Residence Single Story             107
8                         Mobile Home Single Wide             108
9                                          Church             109
10            Motor Home (if used as a residence)             110
11             Multi Family Residence Multi Story             111
12                   Mixed Commercial/Residential             112
13                Commercial Building Multi Story             113
14                        Mobile Home Triple Wide             114
15                                         School             115
16                                           None             116

In [19]:
structuretype_codes.to_csv(
    "/capstone/wildfire_prep/data/metadata/structuretype_codes.csv",
    index=False,
)

In [27]:
inspections

       inspection_id                                     structuret
0                  1  Utility or Miscellaneous Structure > 120 sqft
1                  2            Single Family Residence Multi Story
2                  3            Single Family Residence Multi Story
3                  4  Utility or Miscellaneous Structure > 120 sqft
4                  5            Single Family Residence Multi Story
...              ...                                            ...
67575          67576            Single Family Residence Multi Story
67576          67577                                           None
67577          67578                        Mobile Home Double Wide
67578          67579                        Mobile Home Double Wide
67579          67580           Single Family Residence Single Story

[67580 rows x 2 columns]

In [37]:
inspections = inspections.merge(
    structuretype_codes[["structuret", "structure_code"]],
    on="structuret",
    how="left",
).drop(columns=["structuret"])
inspections

       inspection_id  structure_code
0                  1             100
1                  2             101
2                  3             101
3                  4             100
4                  5             101
...              ...             ...
67575          67576             101
67576          67577             116
67577          67578             106
67578          67579             106
67579          67580             102

[67580 rows x 2 columns]

In [38]:
inspections.to_csv(
    "/capstone/wildfire_prep/data/PUZZLE_PIECES/inspections_id_structure_type.csv",
    index=False,
)