### Loading SB County Rainfall Data

- Rain gauge data downloaded from the hydrology section of the Santa Barbara County website
- Need to determine the number of rain gauges we are using data from

#### Steps
- Clean data from

In [1]:
# Load packages
import os
import sys
import numpy as np
import pandas as pd
import geopandas as gpd

import os
import sys

sys.path.append("../utils")

import config

In [2]:
rain_gauge = os.path.join(
    config.data_dir,
    "sb_rain_gauges",
    "155dailys.xls"
)
rain_test = pd.read_excel(rain_gauge, header = 9)

In [3]:
test = pd.read_excel(rain_gauge, nrows = 8, usecols="A")
test

                             County of Santa Barbara
0        Daily Rainfall Record - through 08-31-2023
1                                                NaN
2                           #155 - East Camino Cielo
3         Lat 34-28-58, Long 119-38-15, Elev 3450 ft
4                                                NaN
5  Daily Rainfall (in inches) recorded as of 8am ...
6  Codes: PR = Preliminary data,  E = Estimated f...
7                                                NaN

In [ ]:
# Function to convert Degrees-Minutes-Seconds to Decimal Degrees
def dms_to_decimal(dms):
    degrees, minutes, seconds = map(int, dms.split('-'))
    return degrees + (minutes / 60) + (seconds / 3600)

In [7]:
# 
rain_test[['lat', 'long', 'elevation']] = (test['County of Santa Barbara'].dropna()
                                           .loc[lambda x: x.str.startswith('L')]
                                           .iloc[0]
                                           .split(', '))

#
rain_test['lat'] = rain_test['lat'].apply(lambda x: x.replace('Lat ', '')).apply(dms_to_decimal)
rain_test['long'] = rain_test['long'].apply(lambda x: x.replace('Long ', '')).apply(dms_to_decimal)
rain_test['elevation'] = rain_test['elevation'].apply(lambda x: int(x.replace('Elev ', '').replace(' ft', '')))
rain_test

,stationid,wy,year,monthnum,day,dailyrain,code,lat,long,elevation
0,155,2019,2018,10,4,0.35,NaN,34.482778,119.6375,3450
1,155,2019,2018,10,5,0.14,NaN,34.482778,119.6375,3450
2,155,2019,2018,10,13,0.02,NaN,34.482778,119.6375,3450
3,155,2019,2018,11,22,0.61,NaN,34.482778,119.6375,3450
4,155,2019,2018,11,29,2.40,NaN,34.482778,119.6375,3450
...,...,...,...,...,...,...,...,...,...,...
327,155,2023,2023,8,10,0.24,NaN,34.482778,119.6375,3450
328,155,2023,2023,8,11,0.12,NaN,34.482778,119.6375,3450
329,155,2023,2023,8,21,0.54,NaN,34.482778,119.6375,3450
330,155,2023,2023,8,22,0.10,NaN,34.482778,119.6375,3450
331,155,2023,2023,8,31,0.00,NaN,34.482778,119.6375,3450